### ISSUE TITLE
Deprecate attributes

### ISSUE THREAD

**Issue by saas786** [virgiliud/animated-blocks#1]
Hi there,

Note: I am using fork of your code, for different purposes.

First of all thanks for your block, this is the only block I found so far which allows me to extend the core blocks without too much fuss.

I have a query though,

as if we register our own block, we have the ability to provide deprecated versions in case we change attributes etc.

but I am struggling to understand how I can provide deprecated code when I am extending the block instead of creating new one. 

Like for example, I tried to add 'default' property to some attribute, and I have saved the block, but I haven't applied attribute using inspector controls (like animation), so if I change 'default' property value in code, and now if I load the page, it throws "This block appears to have been modified externally."

Does it make sense?

**Comment by virgiliud** [comment]
Hi, 

If you change the markup in the save method you will get a block validation error. Gutenberg expects the new markup to match what was already stored in post content, otherwise the block will be marked as invalid. Blocks are validated to protect against content loss.

I reported a similar issue in the Gutenberg repo and it is expected behavior. Hopefully it will be improved in a future release.

**Comment by saas786** [comment]
Hi,

If I were using save method, (like creating my own block, I think I would have managed to created deprecated function for old attributes etc), it would not have been an issue.

But I am using extend block approach, used in your code. So I am unable to grasp the concept and implement it in this case. I have tried various hit & trial changes, but none work.

So I was hoping you might have a better understanding and can point me in right direction, as it relates to your code as well, in case if you change your attributes default values, it will break the code.

Let me know your further thoughts. Thanks

**Comment by virgiliud** [comment]
The filters in the extended block approach apply to the save function. 

I think the [registerBlockType](https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#modifying-blocks) filter should be investigated if trying adding deprecated properties. 

I encourage to inquire about this type of extensibility in [Gutenberg repo](https://github.com/WordPress/gutenberg/labels/Extensibility) as this is still experimental. Related issue: https://github.com/WordPress/gutenberg/issues/6856
