### ISSUE TITLE
3rd party block compatibility

### ISSUE THREAD

**Issue by adrolli** [virgiliud/animated-blocks#4]
Heyy @virgiliud 

Very nice plugin. I love it!

Animated Blocks works well with all official Gutenberg blocks but not with 3rd party blocks like CoBlocks or Atomic Blocks. In edit post the animation first seems to work, but not in the preview or saved post. Getting back to the edit post no values are saved. The animation is "None" while custom class, delay and threshold are empty.

I tested with WP 4.9.8 and Gutenberg 3.6.2 on different WP-installs using different themes and browser. Also tried `animated infinite bounce delay-2s` in the Additional CSS Class as a workaround. The animation works on page load but is not triggered by scrolling.

Cheers,
Alf

**Comment by virgiliud** [comment]
Hey @adrolli thanks!

I made Animated Blocks to work primarily with the core Gutenberg blocks. You can try wrapping third party blocks in Gutenberg column blocks. Include third party blocks inside each column and add the animations to the columns.

**Comment by adrolli** [comment]
Hey @virgiliud 

thanks for the reply. That works well. Good workaround. Will do some animated experiments now ;-)

**Comment by virgiliud** [comment]
@adrolli I updated the plugin to support inner blocks. The animation block now acts like the column block. You can add whatever blocks you want inside the animation blocks.
