### ISSUE TITLE
Block should appear only after scroll for some effects like bouncein, fadein etc.

### ISSUE THREAD

**Issue by jaynarayan89** [virgiliud/animated-blocks#6]
It would be great if we have setting for hiding the block initially and  reveal it only after scroll.
[demo]( https://woo-restaurant.com/order-date-time-pickup-location-documentation/order-date-time-and-pickup-location-documentation/)

**Comment by virgiliud** [comment]
Hey @jaynarayan89 it already has that feature. You have to toggle on "Set to 0 opacity" and the block will be at 0 opacity. This works with animations that end with opacity 1 in the CSS. Otherwise you just have to add some custom CSS.
